# Generated by Django 4.1.5 on 2023-11-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbook',
            name='bookprice',
            field=models.CharField(max_length=10),
        ),
    ]
